<?php return array (
  'util' => 
  array (
    'u' => 'lutil@mailinator.com',
    'p' => 'qweqwe123',
    'x' => 32,
    'y' => 32,
  ),
  'limitium' => 
  array (
    'u' => 'limitium@gmail.com',
    'p' => 'qweqwe123',
    'x' => 32,
    'y' => 32,
  ),
  10 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => '1st Closed Beta server. Slots for 25,000 players.',
    'Id' => 10,
    'Language' => 'en',
    'Name' => 'Closed Beta 1',
    'StartTime' => 1.3238712E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame02.alliances.commandandconquer.com/10',
    'x' => 32,
    'y' => 32,
    'p' => 'Twilight4',
    'u' => 'calalasse@gmail.com',
  ),
  11 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => '2nd Closed Beta server. Slots for 50,000 players.',
    'Id' => 11,
    'Language' => 'en',
    'Name' => 'Closed Beta 2',
    'StartTime' => 1.3291236E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame03.alliances.commandandconquer.com/11',
    'x' => 50,
    'y' => 50,
    'p' => '971385200',
    'u' => 'Vegacyrez@hotmail.com',
  ),
  12 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => '3rd Closed Beta server. Slots for 25,000 players.',
    'Id' => 12,
    'Language' => 'en',
    'Name' => 'Closed Beta 3',
    'StartTime' => 1.3305114E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame04.alliances.commandandconquer.com/12',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'limitium@gmail.com',
  ),
  13 => 
  array (
    'AcceptNewPlayer' => false,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 13,
    'Language' => 'en',
    'Name' => 'World 4 (Europe)',
    'StartTime' => 1.3317192E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame05.alliances.commandandconquer.com/13',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lworld4@mailinator.com',
  ),
  14 => 
  array (
    'AcceptNewPlayer' => false,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 14,
    'Language' => 'en',
    'Name' => 'World 5 (USA East Coast)',
    'StartTime' => 1.3317192E+12,
    'Timezone' => -4,
    'Url' => 'http://prodgame05.alliances.commandandconquer.com/14',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lworld5@mailinator.com',
  ),
  15 => 
  array (
    'AcceptNewPlayer' => false,
    'Description' => 'Slots für 25,000 Spieler.',
    'Id' => 15,
    'Language' => 'de',
    'Name' => 'Welt 1',
    'StartTime' => 1.3317192E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame08.alliances.commandandconquer.com/15',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lwelt1@mailinator.com',
  ),
  16 => 
  array (
    'AcceptNewPlayer' => false,
    'Description' => 'Slots für 25,000 Spieler.',
    'Id' => 16,
    'Language' => 'de',
    'Name' => 'Welt 2',
    'StartTime' => 1.3324932E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame08.alliances.commandandconquer.com/16',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lwelt2@mailinator.com',
  ),
  17 => 
  array (
    'AcceptNewPlayer' => false,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 17,
    'Language' => 'en',
    'Name' => 'World 6 (Europe)',
    'StartTime' => 1.3318992E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame05.alliances.commandandconquer.com/17',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lworld6@mailinator.com',
  ),
  18 => 
  array (
    'AcceptNewPlayer' => false,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 18,
    'Language' => 'en',
    'Name' => 'World 7 (Europe)',
    'StartTime' => 1.3321494E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame05.alliances.commandandconquer.com/18',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lworld7@mailinator.com',
  ),
  19 => 
  array (
    'AcceptNewPlayer' => false,
    'Description' => 'Slots für 25,000 Spieler.',
    'Id' => 19,
    'Language' => 'de',
    'Name' => 'Welt 3',
    'StartTime' => 1.3333536E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame08.alliances.commandandconquer.com/19',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lwelt3@mailinator.com',
  ),
  20 => 
  array (
    'AcceptNewPlayer' => false,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 20,
    'Language' => 'en',
    'Name' => 'World 8 (USA East Coast)',
    'StartTime' => 1.3325004E+12,
    'Timezone' => -4,
    'Url' => 'http://prodgame02.alliances.commandandconquer.com/20',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lworld8@mailinator.com',
  ),
  21 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 21,
    'Language' => 'en',
    'Name' => 'World 9 (USA West Coast)',
    'StartTime' => 1.3325004E+12,
    'Timezone' => -7,
    'Url' => 'http://prodgame03.alliances.commandandconquer.com/21',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lworld9@mailinator.com',
  ),
  24 => 
  array (
    'AcceptNewPlayer' => false,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 24,
    'Language' => 'en',
    'Name' => 'World 10 (Europe)',
    'StartTime' => 1.3325868E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame02.alliances.commandandconquer.com/24',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lworld10@mailinator.com',
  ),
  25 => 
  array (
    'AcceptNewPlayer' => false,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 25,
    'Language' => 'en',
    'Name' => 'World 11 (Europe)',
    'StartTime' => 1.3333536E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame03.alliances.commandandconquer.com/25',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lworld11@mailinator.com',
  ),
  26 => 
  array (
    'AcceptNewPlayer' => false,
    'Description' => 'Slots für 25,000 Spieler.',
    'Id' => 26,
    'Language' => 'de',
    'Name' => 'Welt 4',
    'StartTime' => 1.3368168007E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame08.alliances.commandandconquer.com/26',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lwelt4@mailinator.com',
  ),
  27 => 
  array (
    'AcceptNewPlayer' => false,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 27,
    'Language' => 'en',
    'Name' => 'World 12 (Europe)',
    'StartTime' => 1.3337055E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame04.alliances.commandandconquer.com/27',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lworld12@mailinator.com',
  ),
  28 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 28,
    'Language' => 'en',
    'Name' => 'World 13 (USA East Coast)',
    'StartTime' => 1.3343256E+12,
    'Timezone' => -4,
    'Url' => 'http://prodgame02.alliances.commandandconquer.com/28',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lworld13@mailinator.com',
  ),
  29 => 
  array (
    'AcceptNewPlayer' => false,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 29,
    'Language' => 'en',
    'Name' => 'World 15 (Europe)',
    'StartTime' => 1.3359708E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame03.alliances.commandandconquer.com/29',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lworld15@mailinator.com',
  ),
  30 => 
  array (
    'AcceptNewPlayer' => false,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 30,
    'Language' => 'en',
    'Name' => 'World 14 (Europe)',
    'StartTime' => 1.3345608E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame04.alliances.commandandconquer.com/30',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lworld14@mailinator.com',
  ),
  31 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 31,
    'Language' => 'en',
    'Name' => 'World 16 (Europe)',
    'StartTime' => 1.33706520043E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame05.alliances.commandandconquer.com/31',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lworld16@mailinator.com',
  ),
  32 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 32,
    'Language' => 'en',
    'Name' => 'World 17 (USA East Coast)',
    'StartTime' => 1.33769160043E+12,
    'Timezone' => -4,
    'Url' => 'http://prodgame02.alliances.commandandconquer.com/32',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lworld17@mailinator.com',
  ),
  33 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 33,
    'Language' => 'en',
    'Name' => 'World 18 (Europe)',
    'StartTime' => 1.33784640064E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame03.alliances.commandandconquer.com/33',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lworld18@mailinator.com',
  ),
  34 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 34,
    'Language' => 'en',
    'Name' => 'World 19 (USA West Coast)',
    'StartTime' => 1.33784640064E+12,
    'Timezone' => -7,
    'Url' => 'http://prodgame04.alliances.commandandconquer.com/34',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lworld19@mailinator.com',
  ),
  36 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 36,
    'Language' => 'en',
    'Name' => 'World 21 (Europe)',
    'StartTime' => 1.33839E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame04.alliances.commandandconquer.com/36',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lworld21@mailinator.com',
  ),
  37 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Emplacements pour 25 000 joueurs.',
    'Id' => 37,
    'Language' => 'fr',
    'Name' => 'Monde 1',
    'StartTime' => 1.33784640064E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame07.alliances.commandandconquer.com/37',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lmonde1@mailinator.com',
  ),
  38 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slot per 25.000 giocatori.',
    'Id' => 38,
    'Language' => 'it',
    'Name' => 'Mondo 1',
    'StartTime' => 1.33784640064E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame07.alliances.commandandconquer.com/38',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lmondo1@mailinator.com',
  ),
  39 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Espacios para 25.000 jugadores.',
    'Id' => 39,
    'Language' => 'es',
    'Name' => 'Mundo 1 (España)',
    'StartTime' => 1.33784640064E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame07.alliances.commandandconquer.com/39',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lmundoe1@mailinator.com',
  ),
  40 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Miejsca dla 25 000 graczy.',
    'Id' => 40,
    'Language' => 'pl',
    'Name' => 'Świat 1',
    'StartTime' => 1.33784640064E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame07.alliances.commandandconquer.com/40',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lswait1@mailinator.com',
  ),
  41 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Ячейки для 25 000 игроков.
',
    'Id' => 41,
    'Language' => 'ru',
    'Name' => 'Мир 1',
    'StartTime' => 1.33784640064E+12,
    'Timezone' => 4,
    'Url' => 'http://prodgame09.alliances.commandandconquer.com/41',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lmir1@mailinator.com',
  ),
  42 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Entradas para 25 000 jogadores.',
    'Id' => 42,
    'Language' => 'pt',
    'Name' => 'Mundo 1 (Portuguesa)',
    'StartTime' => 1.33784640064E+12,
    'Timezone' => 1,
    'Url' => 'http://prodgame09.alliances.commandandconquer.com/42',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lmundop1@mailinator.com',
  ),
  43 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => '25.000 oyuncu alır',
    'Id' => 43,
    'Language' => 'tr',
    'Name' => 'Dünya 1',
    'StartTime' => 1.33784640064E+12,
    'Timezone' => 3,
    'Url' => 'http://prodgame09.alliances.commandandconquer.com/43',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'ldunya1@mailinator.com',
  ),
  44 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots voor 25.000 spelers.',
    'Id' => 44,
    'Language' => 'nl',
    'Name' => 'Wereld 1',
    'StartTime' => 1.33784640064E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame09.alliances.commandandconquer.com/44',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lwereld1@mailinator.com',
  ),
  45 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Espaços para 25.000 jogadores.',
    'Id' => 45,
    'Language' => 'pt',
    'Name' => 'Mundo 1 Brazil',
    'StartTime' => 1.33784640064E+12,
    'Timezone' => -3,
    'Url' => 'http://prodgame09.alliances.commandandconquer.com/45',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lmundob1@mailinator.com',
  ),
  46 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots für 25,000 Spieler.',
    'Id' => 46,
    'Language' => 'de',
    'Name' => 'Welt 5',
    'StartTime' => 1.33830000064E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame07.alliances.commandandconquer.com/46',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lwelt5@mailinator.com',
  ),
  47 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Emplacements pour 25 000 joueurs.',
    'Id' => 47,
    'Language' => 'fr',
    'Name' => 'Monde 2',
    'StartTime' => 1.33916040046E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame06.alliances.commandandconquer.com/47',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lmonde2@mailinator.com',
  ),
  49 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Espacios para 25.000 jugadores.',
    'Id' => 49,
    'Language' => 'es',
    'Name' => 'Mundo 2 (España)',
    'StartTime' => 1.33942710046E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame12.alliances.commandandconquer.com/49',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lmundoe2@mailinator.com',
  ),
  52 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Ячейки для 25 000 игроков.',
    'Id' => 52,
    'Language' => 'ru',
    'Name' => 'Мир 2',
    'StartTime' => 1.3400298E+12,
    'Timezone' => 4,
    'Url' => 'http://prodgame12.alliances.commandandconquer.com/52',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lmir2@mailinator.com',
  ),
  55 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Espaços para 25.000 jogadores.',
    'Id' => 55,
    'Language' => 'pt',
    'Name' => 'Mundo 2 Brazil',
    'StartTime' => 1.34037000097E+12,
    'Timezone' => -3,
    'Url' => 'http://prodgame12.alliances.commandandconquer.com/55',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lmundob2@mailinator.com',
  ),
  56 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 56,
    'Language' => 'en',
    'Name' => 'World 22 (USA East Coast)',
    'StartTime' => 1.33865280018E+12,
    'Timezone' => -4,
    'Url' => 'http://prodgame05.alliances.commandandconquer.com/56',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lworld22@mailinator.com',
  ),
  57 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 57,
    'Language' => 'en',
    'Name' => 'World 23 (Europe)',
    'StartTime' => 1.33883280089E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame03.alliances.commandandconquer.com/57',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lworld23@mailinator.com',
  ),
  58 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots für 25,000 Spieler.',
    'Id' => 58,
    'Language' => 'de',
    'Name' => 'Welt 6',
    'StartTime' => 1.33916040046E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame07.alliances.commandandconquer.com/58',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lwelt6@mailinator.com',
  ),
  59 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.#',
    'Id' => 59,
    'Language' => 'en',
    'Name' => 'World 24 (Europe)',
    'StartTime' => 1.33942710046E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame11.alliances.commandandconquer.com/59',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lworld24@mailinator.com',
  ),
  60 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 60,
    'Language' => 'en',
    'Name' => 'World 25 (USA West Coast)',
    'StartTime' => 1.33958160044E+12,
    'Timezone' => -7,
    'Url' => 'http://prodgame11.alliances.commandandconquer.com/60',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lworld25@mailinator.com',
  ),
  61 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 61,
    'Language' => 'en',
    'Name' => 'World 26 (USA East Coast)',
    'StartTime' => 1.33958160044E+12,
    'Timezone' => -4,
    'Url' => 'http://prodgame11.alliances.commandandconquer.com/61',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lworld26@mailinator.com',
  ),
  62 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => NULL,
    'Id' => 62,
    'Language' => 'en',
    'Name' => 'World 27 (Europe)',
    'StartTime' => 1.34011800097E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame11.alliances.commandandconquer.com/62',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lworld27@mailinator.com',
  ),
  64 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots für 25,000 Spieler.',
    'Id' => 64,
    'Language' => 'de',
    'Name' => 'Welt 7',
    'StartTime' => 1.34037000097E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame12.alliances.commandandconquer.com/64',
    'x' => 32,
    'y' => 32,
    'p' => 'qweqwe123',
    'u' => 'lwelt7@mailinator.com',
  ),
  65 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Emplacements pour 25 000 joueurs.',
    'Id' => 65,
    'Language' => 'fr',
    'Name' => 'Monde 3',
    'StartTime' => 1.34088840055E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame12.alliances.commandandconquer.com/65',
    'x' => 32,
    'y' => 32,
    'u' => 'lmonde3@mailinator.com',
    'p' => 'qweqwe123',
  ),
  66 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 66,
    'Language' => 'en',
    'Name' => 'World 28 (USA East Coast)',
    'StartTime' => 1.34097480057E+12,
    'Timezone' => -4,
    'Url' => 'http://prodgame11.alliances.commandandconquer.com/66',
    'x' => 32,
    'y' => 32,
    'u' => 'lworld28@mailinator.com',
    'p' => 'qweqwe123',
  ),
  67 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 67,
    'Language' => 'en',
    'Name' => 'World 29 (Europe)',
    'StartTime' => 1.34097480057E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame11.alliances.commandandconquer.com/67',
    'x' => 32,
    'y' => 32,
    'u' => 'lworld29@mailinator.com',
    'p' => 'qweqwe123',
  ),
  68 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots für 25,000 Spieler.',
    'Id' => 68,
    'Language' => 'de',
    'Name' => 'Welt 8',
    'StartTime' => 1.3415796003E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame12.alliances.commandandconquer.com/68',
    'x' => 32,
    'y' => 32,
    'u' => 'lwelt8@mailinator.com',
    'p' => 'qweqwe123',
  ),
  35 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 35,
    'Language' => 'en',
    'Name' => 'World 30 (Europe)',
    'StartTime' => 1.34182800022E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame03.alliances.commandandconquer.com/35',
    'x' => 32,
    'y' => 32,
    'u' => 'lworld30@mailinator.com',
    'p' => 'qweqwe123',
  ),
  69 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Espacios para 25.000 jugadores.',
    'Id' => 69,
    'Language' => 'es',
    'Name' => 'Mundo 3 (España)',
    'StartTime' => 1.34217000026E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame12.alliances.commandandconquer.com/69',
    'x' => 32,
    'y' => 32,
    'u' => 'l@mailinator.com',
    'p' => 'qweqwe123',
  ),
  70 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 70,
    'Language' => 'en',
    'Name' => 'World 31 (USA West Coast)',
    'StartTime' => 1.34228880032E+12,
    'Timezone' => -7,
    'Url' => 'http://prodgame11.alliances.commandandconquer.com/70',
    'x' => 32,
    'y' => 32,
    'u' => 'l@mailinator.com',
    'p' => 'qweqwe123',
  ),
  71 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Slots for 25,000 players.',
    'Id' => 71,
    'Language' => 'en',
    'Name' => 'World 32 (USA East Coast)',
    'StartTime' => 1.3424436009E+12,
    'Timezone' => -4,
    'Url' => 'http://prodgame11.alliances.commandandconquer.com/71',
    'x' => 32,
    'y' => 32,
    'u' => 'l@mailinator.com',
    'p' => 'qweqwe123',
  ),
  72 => 
  array (
    'AcceptNewPlayer' => true,
    'Description' => 'Emplacements pour 25 000 joueurs.',
    'Id' => 72,
    'Language' => 'fr',
    'Name' => 'Monde 4',
    'StartTime' => 1.3424436009E+12,
    'Timezone' => 2,
    'Url' => 'http://prodgame12.alliances.commandandconquer.com/72',
    'x' => 32,
    'y' => 32,
    'u' => 'l@mailinator.com',
    'p' => 'qweqwe123',
  ),
);